sudo: false

language: objective-c
env:
  matrix:
    - VERSION=2.6.9
    - VERSION=2.7.11
    - VERSION=3.3.6
    - VERSION=3.4.4
    - VERSION=3.5.1

install:
  - source terryfy/travis_tools.sh
  - get_python_environment macpython $VERSION venv
  - pip install -U wheel pytest hypothesis
  - cd datrie
  - python setup.py bdist_wheel
  - rename_wheels dist
  - pip install dist/*.whl
  - cd ..

script:
  - mkdir tmp_for_test
  - cd tmp_for_test
  - python -c \"import pytest; pytest.main()\" -s -v datrie
  - cd ..
